import './globals.css'
import type { Metadata } from 'next'
import { Inter, Inter_Tight } from 'next/font/google'

const inter = Inter_Tight({subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mehmet CNR',
  description: 'Generated by create next app',
}


export default function RootLayout({
  
  children,
}: { 
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='bg-body text-gray-200 w-full h-full'>
        {children}
        </div>
        </body>
    </html> 
  )
}
